# Generated by Django 5.1.7 on 2025-03-24 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_duration'),
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='course',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
    ]
